---
- name: Update apt-cache
  apt:
    update_cache: true
  when:
    - ansible_os_family == 'Debian'
    - not haproxy_cfg_only
  tags:
    - install

- name: Ensure HAProxy is installed.
  package:
    name: haproxy
    state: present
  when:
    - not haproxy_cfg_only
  tags:
    - install

- name: Ensure HAProxy is enabled (so init script will start it on Debian).
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED.+$"
    line: "ENABLED=1"
    state: present
  when:
    - ansible_os_family == 'Debian'
    - not haproxy_cfg_only
  tags:
    - install

- name: Copy HAProxy configuration in place.
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_cfg_dest }}"
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    mode: 0644
  notify: restart haproxy
  tags:
    - configuration

- name: Copy SSL Certs to HAProxy server if SSL is enabled.
  copy:
    src: "{{ item.1.pem_local }}"
    dest: "{{ item.1.pem_proxy }}"
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    mode: 0400
  with_subelements:
    - "{{ haproxy_frontends }}"
    - bind
  when:
    - item.1.ssl is defined
    - item.1.pem_local is defined
    - item.1.pem_proxy is defined
    - item.1.ssl
  tags:
    - configuration

- name: Ensure HAProxy is started and enabled on boot.
  service:
    name: "{{ haproxy_service_name }}"
    state: started
    enabled: true
  when:
    - not haproxy_cfg_only
  tags:
    - install
