---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Verify that haproxy is running on port 80
      uri:
        url: http://127.0.0.1/
        url_username: test
        url_password: abc123
        status_code: 503
